### ISSUE TITLE
Possible Incompatibility

### ISSUE THREAD

**Issue by skacurt** [jobeid/TrayPwrD3#1]
Fails to run with the following config.

**OS:**
Microsoft Windows Version 1709 (OS Build 10.0.16299.214) 
(Windows Defender is enabled)

**Hardware:**
Intel(R) HD Graphics 3000
NVIDIA GeForce GT 540M

**Event Log:**
> Faulting application name: TrayPwrD3.exe, version: 1.5.0.0, time stamp: 0x5a200ef1
> Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x4736733c
> Exception code: 0xc000041d
> Fault offset: 0x0000000000013fb8
> Faulting process id: 0x1b8c
> Faulting application start time: 0x01d39f6ad8490a14
> Faulting application path: C:\traypwrd3\TrayPwrD3.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: fa300cde-a00b-4674-8f03-6503fc9b2c9c
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by jobeid** [comment]
Can't reproduce on exact same Windows Version 1709 (OS Build 10.0.16299.214) and Windows Defender is enabled with 
Intel(R) HD Graphics 530
NVIDIA GeForce GTX 1060

Can you check what the Preferred Graphics Processor is in the NVIDIA control panel (auto-select, integrated graphics, or NVIDIA?)

**Comment by skacurt** [comment]
The global setting is `auto-select` and  I can say that there's no custom setting for `TrayPwrD3.exe`.

**Comment by jobeid** [comment]
What's the NVIDIA driver version and DirectX version (for directX see: https://support.microsoft.com/en-us/help/157730/how-to-determine-the-version-of-directx-by-using-the-directx-diagnosti)

**Comment by skacurt** [comment]
Diagnostic reports attached.

[NVIDIA System Information 02-17-2018 19-07-52.txt](https://github.com/jobeid/TrayPwrD3/files/1733825/NVIDIA.System.Information.02-17-2018.19-07-52.txt)
[DxDiag.txt](https://github.com/jobeid/TrayPwrD3/files/1733826/DxDiag.txt)

**Comment by jobeid** [comment]
Ok. I think I see the problem, the Direct3D API version has to be 12. Yours is 11.
Direct3D API version:	12
Direct3D feature level:	12_1

I'll look into backward compatibility...

**Comment by skacurt** [comment]
I see.
Please let me know if I can do something to help, memory dump, binary examples etc.

Thanks for your time.
